/*
This code was generated by Github Copilot, and Amo wrote the requirements needed to generate the code. The requirements are as follows:

Help me generate a C language program that reads the bin file and then encrypts it using the xor table. 
There are 2 sets of Xor tables, using different 4-byte length fixed strings as keys. 
It is required to first obtain the total number of packages based on the file size by 1KB. 
Note that the last package may be less than 1KB, and then perform a set of encryption for each package and execute it in a loop every 3K. 
The first KB keeps the original text unencrypted, the 2KB is encrypted using the first Xor table, and the 3KB is encrypted using the second Xor table. 
When performing xor encryption, it is necessary to judge the status of each byte. If the value of the byte is 0 or 0xFF, or this byte is the same as the Xor key byte, or the byte is equal to the xor key XOR 0xFF , this byte is not encrypted. 
The first two packages and the last two packages need to keep the original text without encryption, and the input file and output file are required to be passed in using parameters.
*/

#include <stdio.h>
#include <stdlib.h>

#define PACKAGE_SIZE 1024 // 1KB
#define XOR_KEY1 "KDHT"
#define XOR_KEY2 "RBGI"

void xor_encrypt(uint8_t *data, char *key, int len) {
  for (int i = 0; i < len; i++) {
    uint8_t byte = data[i];
    if (byte != 0 && byte != 0xFF && byte != key[i % 4] &&
        byte != (key[i % 4] ^ 0xFF)) {
      data[i] ^= key[i % 4];
    }
  }
}

int main(int argc, char *argv[]) {
  if (argc != 3) {
    printf("Usage: %s <input file> <output file>\n", argv[0]);
    return 1;
  }

  FILE *input = fopen(argv[1], "rb");
  FILE *output = fopen(argv[2], "wb");

  if (!input || !output) {
    printf("Error opening file.\n");
    return 1;
  }

  fseek(input, 0, SEEK_END);
  long file_size = ftell(input);
  rewind(input);

  int package_count = file_size / PACKAGE_SIZE;
  int last_package_size = file_size % PACKAGE_SIZE;
  if (last_package_size > 0) {
    package_count++;
  }
  
  uint8_t *buffer = (uint8_t *)malloc(PACKAGE_SIZE);

  for (int i = 0; i < package_count; i++) {
    int current_package_size = (i == package_count - 1 && last_package_size > 0)
                                   ? last_package_size
                                   : PACKAGE_SIZE;
    fread(buffer, current_package_size, 1, input);

    if (i >= 2 && i < package_count - 2) {
      if (i % 3 == 1) {
        xor_encrypt(buffer, XOR_KEY1, current_package_size);
      } else if (i % 3 == 2) {
        xor_encrypt(buffer, XOR_KEY2, current_package_size);
      }
    }

    fwrite(buffer, current_package_size, 1, output);
  }

  free(buffer);
  fclose(input);
  fclose(output);

  return 0;
}